FROM golang:1.23.5-alpine

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /migrations

# Copy migration files and scripts
COPY server/db/migrations/*.sql ./migrations/
COPY server/Makefile ./Makefile

# Set environment variables

ENTRYPOINT ["make", "migrate_up"]