services:
  postgres:
    container_name: golang_postgres_local
    image: postgres:16.6
    shm_size: 1g
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./.docker/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - golang_postgres_local:/var/lib/postgresql/data
    networks:
      - golang
  pgadmin:
    container_name: golang_pgadmin_local
    image: dpage/pgadmin4:8.14.0
    shm_size: 1g
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - golang_pgadmin_local:/var/lib/pgadmin
    networks:
      - golang
networks:
  golang:
volumes:
  golang_postgres_local:
  golang_pgadmin_local:
