info:
  contact: {}
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Get a list of all available articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List all articles
      tags:
      - articles
  /articles/{id}:
    get:
      consumes:
      - application/json
      description: Get article details by its ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get article by ID
      tags:
      - articles
swagger: "2.0"
